#!/usr/bin/env ansible-playbook
# This playbook calls in to tasks/setup_app_server.yml, which calls in into setup_server.yml.
# It'll install all base packages, set up apache2, etc.

- name: Setup base webserver system
  hosts: "{{ hosts }}"
  remote_user: root

  vars_files:
    - ../global_vars.yml

  tasks:
    - include: "{{ ANSIBLE_ROOT }}/tasks/setup_app_server.yml"
