#!/usr/bin/env ansible-playbook
# This playbook calls in to setup_database_server.yml task, which calls in into setup_server.yml.
# It'll install all base packages, set up postgresql, etc.

- name: Setup BubbleCK servers
  hosts: "{{ hosts }}"
  remote_user: root

  vars_files:
    - ../global_vars.yml
    - ../vars/users.yml

  vars_prompt:
    - name: "build_opencv"
      prompt: "Build OpenCV Libraries?"
      default: "no"

  handlers:
    - include: "{{ ANSIBLE_ROOT }}/handlers/main.yml"

  tasks:
    - include: "{{ ANSIBLE_ROOT }}/tasks/setup_server.yml"
    - include: "{{ ANSIBLE_ROOT }}/tasks/setup_database_server.yml"
      when: "'database' in roles"
    - include: "{{ ANSIBLE_ROOT }}/tasks/setup_app_server.yml"
      when: "'appserver' in roles"
    - include: "{{ ANSIBLE_ROOT }}/tasks/install_opencv.yml"
      when: "'appserver' in roles and build_opencv == 'yes'"
