- name: Upgrade Ubuntu Packages
  apt: upgrade=dist update_cache=yes

# Install generic packages that all servers should have:
- name: Install Packages
  apt:  pkg={{ item }} state=present
  with_items:
    - bpython3
    - cups
    - elinks
    - ethtool
    - git
    - htop
    - iftop
    - iotop
    - less
    - libpython3.4 
    - libpython3.4-minimal 
    - libpython3.4-stdlib 
    - links
    - python
    - python3-bcrypt
    - python3-openssl
    - python3-psycopg2
    - python3-simplejson
    - python3.4
    - python3.4-minimal
    - rsync
    - smbclient
    - subversion
    - unzip
    - wget
    - zip


- name: Upload some helpful scripts
  copy: "src={{ ANSIBLE_ROOT }}/files/{{ item }} dest=/usr/local/bin/"
  with_items:
    - psre

- include: update_users.yml

- include: update_shared_python.yml
