- name: Upgrade Ubuntu Packages
  apt: upgrade=dist update_cache=yes

# Install generic packages that all servers should have:
- name: Install Packages
  apt:  pkg={{ item }} state=present
  with_items:
    - bpython
    - cups
    - elinks
    - ethtool
    - git
    - htop
    - iftop
    - iotop
    - less
    - links
    - python
    - python-bcrypt
    - python-openssl
    - python-psycopg2
    - python-simplejson
    - rsync
    - subversion
    - smbclient
    - unzip
    - wget
    - zip

- name: Upload some helpful scripts
  copy: "src={{ ANSIBLE_ROOT }}/files/{{ item }} dest=/usr/local/bin/"
  with_items:
    - psre

- include: update_users.yml

- include: update_shared_python.yml
