# Include generic packages:
- name: Install web-server specific packages
  apt: pkg={{ item }} state=present
  with_items:
    - apache2
    - libapache2-mod-wsgi-py3
    - libopencv-dev
    - postgresql-client
    - python3-flask
    - python3-jinja2

- name: Set Up Apache2 Log Directories
  file: path=/var/log/apache2/{{ item }} state=directory owner=www-data group=adm mode=755
  with_items:
    - api
    - myautota

- include: "{{ ANSIBLE_ROOT }}/tasks/update_apache2.yml"
