- name: Check out shared python packages
  subversion: repo=https://github.com/taylorreece/bubbleck/trunk/shared_python/{{ item }} dest=/usr/lib/python3.4/{{ item }}
  with_items:
    - bck
    - wtforms
    - flask_wtf

- name: Upload global variables file for python packages
  template: "src={{ ANSIBLE_ROOT }}/templates/bckconfig.py.j2 dest=/usr/lib/python3.4/bck/bckconfig.py mode=644"
