- name: Check out shared python packages
  subversion: repo=https://github.com/taylorreece/myautota/trunk/shared_python/mat dest=/usr/lib/python3.4/mat

- name: Upload global variables file for python packages
  template: "src={{ ANSIBLE_ROOT }}/templates/matconfig.py.j2 dest=/usr/lib/python3.4/mat/matconfig.py mode=644"
