- name: Set Up Apache2 Log Directories
  file: path=/var/log/apache2/{{ item }} state=directory owner=www-data group=adm mode=755
  with_items:
    - bubbleck

- name: Get rid of old sites-enabled files
  file: name={{ item }} state=absent
  with_items:
    - /etc/apache2/sites-available/default-ssl.conf
    - /etc/apache2/sites-available/000-default.conf
    - /etc/apache2/sites-enabled/default-ssl.conf
    - /etc/apache2/sites-enabled/000-default.conf
    - /var/www/html
  notify: reload apache2

- name: Check out latest web repository
  subversion: repo=https://github.com/taylorreece/bubbleck/trunk/web dest=/var/www/bubbleck
  notify: reload apache2

- name: Upload up Apache conf files
  template: src={{ ANSIBLE_ROOT }}/templates/apache2/{{ item }}.j2 dest=/etc/apache2/sites-available/{{ item }} owner=root group=root mode=644 backup=yes
  with_items:
    - 000-bubbleck.conf
  notify: reload apache2

- name: Create symbolic links in sites-enabled
  file: src=/etc/apache2/sites-available/{{ item }} dest=/etc/apache2/sites-enabled/{{ item }} state='link' owner=root group=root mode=777
  with_items:
    - 000-bubbleck.conf
  notify: reload apache2

- name: Enable Specific Modules
  apache2_module: name={{ item }} state=present
  with_items:
    - mime
    - ssl
    - wsgi
  notify: reload apache2

- name: Get rid of those pesky ServerName warnings
  shell: "echo 'ServerName localhost' > /etc/apache2/conf-available/servername.conf && /usr/sbin/a2enconf servername"
  notify: reload apache2

- name: Move SSL Certificates to the correct place
  copy: src={{ ANSIBLE_ROOT }}/files/apache2/ssl/{{ item }} dest=/etc/ssl/{{ item }}
  with_items:
    - bubbleck.com.ca-bundle
    - bubbleck.com.crt
  notify: reload apache2

- name: Move the SSL key into place
  copy: src={{ ANSIBLE_ROOT }}/files/apache2/ssl/bubbleck.com.key dest=/etc/ssl/private/bubbleck.com.key
  notify: reload apache2
